Projeto do felipe onorio
moraguma/GamutoWare pull request #119
Opened 2024-03-23 19:39 UTC by onoriofelipe

2024-03-25 23:42 UTC, onoriofelipe commented
Boa noite!
Por motivos de força maior não pude participar do segundo dia do evento e nem mexer muito no código ontem, então estou tentando terminar rapidinho aqui!
Logo que fizer o último commit vou avisar comentando (enquanto isso talvez tenha alguns commits intermediários).

Não sei se é o lugar apropriado pra esse tipo de pergunta, mas lá vai:

1. Eu posso pegar a parte que eu fiz, só meu minijogo, e upar ele no itch.io? (Batendo o olho não vi licença então não tenho certeza (de qualquer jeito eu ia só usar assets copyleft incluindo os que criei))
2. Se eu continuar mexendo no jogo e sei lá, daqui 1 ano eu fizer atualização, vocês aceitam pull request com outros polimentos aleatórios?

Talvez eu apareça na reunião semanal amanhã

Obrigado!

2024-03-26 00:24 UTC, moraguma commented
Oi Felipe! Tranquilo, a gente espera você falar que tá tudo pronto antes de integrar. Respondendo suas perguntas:

1- Claro! O jogo vai pro Gamutoware mas ele é 100% seu. Pode fazer o que quiser com ele
2- Aceitamos sim! A gente vai conversar sobre a integração dos minijogos na próxima reunião e montar um time de gente interessada pra ajudar. Se você topar, a gente adoraria que você participasse pra incluir tanto seu minigame quanto o do resto do pessoal :)

2024-03-26 04:41 UTC, onoriofelipe commented
Versão final inicial terminada, deve dar pra mergear (assumindo que eu não tenha quebrado nada do projeto sem querer)

Emocionante, primeiro jogo que não larguei pela metade :D

2024-04-16 02:13 UTC, onoriofelipe commented
Pronto pra merge, acho?

2024-04-16 02:35 UTC, Gvinfinity requested changes

2024-04-16 02:35 UTC, Gvinfinity commented on test.txt
Remover arquivo inútil

2024-04-16 02:35 UTC, Gvinfinity commented on microjogos/2024S1/seu_projeto/capa.png
Não apagar pasta seu_projeto ainda, gerará conflito com outros PRs

2024-04-16 02:35 UTC, Gvinfinity commented on microjogos/2024S1/projeto_felipe_onorio/cenas/main.gd
- Remover comentários que deixam o código carregado
- Atualmente impossível perder jogo, verificar motivo, talvez o signal win esteja sempre sendo chamado, mesmo sem a condição de vitória

2024-04-16 03:24 UTC, onoriofelipe commented on microjogos/2024S1/seu_projeto/capa.png
Recriei com ctrl c ctrl v do ```master```, parece que tá sem diferenças na pasta agora:
```
$ git diff master..projeto_do_felipe_onorio -- microjogos/2024S1/seu_projeto
```

2024-04-16 03:25 UTC, onoriofelipe commented on microjogos/2024S1/projeto_felipe_onorio/cenas/main.gd
Aspirador de pó nos comentários, sinal verificado emitido na hora errada removido

2024-04-16 03:25 UTC, onoriofelipe commented on test.txt
Inútil arquivo removido

2024-08-04 21:51 UTC, Gvinfinity approved these changes
Mudanças aprovadas, lgtm :rocket:

2024-08-04 21:52 UTC, merged