Add difficulty counter
moraguma/GamutoWare pull request #192
Opened 2024-04-15 05:03 UTC by IsaelGabriel

Every 5 games won, the difficulty increases, and the variable can be accessed via `Global.difficulty`. It's not obligatory that minigames use it, but this will help balance minigames that were once too difficult or too easy.

2024-04-16 02:41 UTC, IsaelGabriel commented
I don't think this is a problem, why shouldn't the player face a minigame with enhanced difficulty after winning several of them? I thought of 2 (non-exclusive) solutions to this problem:
1. Only increase difficulty on 'Infinite' mode
2. Increase the difficulty threshold from 5 to 10 or 15

2024-04-18 16:44 UTC, moraguma commented
@IsaelGabriel Mmmm sure!

I think making it so it only affects Infinite mode is a good idea.

2024-04-18 16:46 UTC, moraguma requested changes
Make it so it only affects infinite mode!

Just food for thought - Why are we dividing the score by five here? At the end of the day, we are giving minigame developers a way to measure the player's progression and do with that number what they will. Why give this difficulty value instead of just the raw score?

2025-04-08 00:33 UTC, closed without merging

2025-04-08 00:34 UTC, IsaelGabriel commented
Code is obsolete, last commit made 12 months ago.