Added projeto-thedeas
moraguma/GamutoWare pull request #62
Opened 2023-04-25 20:17 UTC by RafaelCarro

Fixed main.gd bugs.
Ready for implementation!

2023-04-27 19:38 UTC, GoliasVictor requested changes
Tudo certo, menos o creditos do som, que precisa identificar o autor e obra

Me parece tudo certo
- [x] Som 
- [x] Icone
- [x] Creditos
- [x] Jogo Completo
- [x] Capa
- [x] Tamanho arquivos

2023-04-27 19:38 UTC, GoliasVictor commented on microjogos/2023S1/projeto-thedeas/creditos.gd
> +- Sons: freesound.org
Creditos errados

2023-05-15 19:18 UTC, moraguma commented on microjogos/2023S1/projeto-thedeas/creditos.gd
> +- Sons: freesound.org
O que há de errado nos créditos?

2023-05-15 19:29 UTC, RafaelCarro commented on microjogos/2023S1/projeto-thedeas/creditos.gd
> +- Sons: freesound.org
A música não tem os créditos ao autor, só ao site. Eu tentei achar a música original mas não achei.

2023-05-26 20:01 UTC, merged